<?php 
	 if (Template::$headerFile != '' && file_exists($headerFileName = Template::$templatePath.'global/'.Template::$headerFile.".phtml")){
		include_once($headerFileName);
	 }
?>	 
<div class="body layout_<?php echo Template::$layout; ?>">
	<div class="content">
	<?php 	 
		 if (Template::$leftFile != '' && file_exists($leftFileName = Template::$templatePath.'global/'.Template::$leftFile.".phtml")){
			include_once($leftFileName);
		 }
	?>	 
		<div class="main">
		<?php 	 
			 if (Template::$contentFile != '' && file_exists($contentFileName = self::$templatePath.$module."/".self::$contentFile.".phtml")){
				include_once($contentFileName);
			 }
			 else{
				include_once(self::$templatePath.$module."/global/error_404.phtml");
			 }
		?>	 
		</div>
	<?php 	 
		 if (Template::$rightFile != '' && file_exists($rightFileName = Template::$templatePath.'global/'.Template::$rightFile.".phtml")){
			include_once($rightFileName);
		 }
	?>	 
	</div>
</div>
<?php 	
	 if (Template::$footerFile != '' && file_exists($footerFileName = Template::$templatePath.'global/'.Template::$footerFile.".phtml")){
		include_once($footerFileName);
	 }
?>
