<?php
// d($params);
// d($module);
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"/>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?php echo $app->getPageTitle(); ?></title>
		<meta name="keywords" content="<?php echo $app->getPageMetaKeywords(); ?>">
		<meta name="description" content="<?php echo $app->getPageMetadescription(); ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<script type="text/javascript">var  _BASEURL ="<?php echo _BASEURL ?>" </script>
<?php echo $app->renderCss(); ?>
<?php echo $app->renderJs(); ?>		
    </head>  

    <body class="<?php echo $app->getBodyClass(); ?>">

        <div class="wrapper">
                <div class="page">
				
					<?php if(isset($_SESSION['emp_name'])) { ?>
						<div role="navigation" class="header navbar navbar-inverse navbar-fixed-top">
						  <div class="container">
							<div class="navbar-header">
							  <a href="<?php echo $app->getBaseUrl(); ?>" class="navbar-brand"><?php echo $app->getSiteTitle(); ?></a>
							</div>
							<div class="collapse navbar-collapse">
							  <ul class="nav navbar-nav">
								<li class="active"><a href="<?php echo $app->getBaseUrl(); ?>">Home</a></li>
								<li><a href="<?php echo $app->getBaseUrl(); ?>projects/list">Projects</a></li>
								<li><a href="<?php echo $app->getBaseUrl(); ?>reports/status_report/">Status Report</a></li>												
								<li><a href="<?php echo $app->getBaseUrl(); ?>attendance/leave/">Leave Form</a></li>
								<li><a href="<?php echo $app->getBaseUrl(); ?>contact-us/">Contact</a></li>
							  </ul>
							</div><!--/.nav-collapse -->
						  </div>
						</div> 
					<?php
					}
					else{
						?>
							<div role="navigation" class="header navbar navbar-inverse navbar-fixed-top">
							  <div class="container">
								<div class="navbar-header">
								  <a href="<?php echo $app->getBaseUrl(); ?>" class="navbar-brand"><?php echo $app->getSiteTitle(); ?></a>
								</div>
								<div class="collapse navbar-collapse">
								  <ul class="nav navbar-nav">
									<li><a href="<?php echo $app->getBaseUrl(); ?>">Home</a></li>
									<li><a href="<?php echo $app->getBaseUrl(); ?>users/login/">Login</a></li>
									<li><a href="<?php echo $app->getBaseUrl(); ?>about-us/">About Us</a></li>
									<li><a href="<?php echo $app->getBaseUrl(); ?>contact-us/">Contact</a></li>
								  </ul>
								</div><!--/.nav-collapse -->
							  </div>
							</div> 
						<?php
					}
				?>
				
				<div class="body ">
					<?php 
						if ($error_messages = Template::getSession('err_message')) {
							echo '<div class="container message_text err_message">' . $error_messages . '</div>';
							Template::setSession('err_message');
						}
						if ($success_messages = Template::getSession('suc_message')) {
							echo '<div class="container message_text suc_message">' . $success_messages . '</div>';
							Template::setSession('suc_message');
						}
					?>
