<?php
// d($params);
// d($module);
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"/>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?php echo $obj->getPageTitle(); ?></title>
		<meta name="keywords" content="<?php echo $obj->getPageMetaKeywords(); ?>">
		<meta name="description" content="<?php echo $obj->getPageMetadescription(); ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<script type="text/javascript">var  _BASEURL ="<?php echo _BASEURL ?>" </script>
<?php echo $obj->renderCss(); ?>
<?php echo $obj->renderJs(); ?>		
    </head>  

    <body class="<?php echo $obj->getBodyClass(); ?>">

        <div class="wrapper">
                <div class="page">
				
					<?php if(isset($_SESSION['emp_name'])) { ?>
						<div role="navigation" class="header navbar navbar-inverse navbar-fixed-top">
						  <div class="container">
							<div class="navbar-header">
							  <a href="<?php echo _BASEURL ?>" class="navbar-brand"><?php echo $obj->getSiteTitle(); ?></a>
							</div>
							<div class="collapse navbar-collapse">
							  <ul class="nav navbar-nav">
								<li class="active"><a href="<?php echo _BASEURL ?>">Home</a></li>
								<li><a href="<?php echo _BASEURL ?>projects/list">Projects</a></li>
								<li><a href="<?php echo _BASEURL ?>reports/status_report/">Status Report</a></li>												
								<li><a href="<?php echo _BASEURL ?>attendance/leave/">Leave Form</a></li>
								<li><a href="<?php echo _BASEURL ?>contact-us/">Contact</a></li>
							  </ul>
							</div><!--/.nav-collapse -->
						  </div>
						</div> 
					<?php
					}
					else{
						?>
							<div role="navigation" class="header navbar navbar-inverse navbar-fixed-top">
							  <div class="container">
								<div class="navbar-header">
								  <a href="<?php echo _BASEURL ?>" class="navbar-brand"><?php echo $obj->getSiteTitle(); ?></a>
								</div>
								<div class="collapse navbar-collapse">
								  <ul class="nav navbar-nav">
									<li><a href="<?php echo _BASEURL ?>">Home</a></li>
									<li><a href="<?php echo _BASEURL ?>users/login/">Login</a></li>
									<li><a href="<?php echo _BASEURL ?>about-us/">About Us</a></li>
									<li><a href="<?php echo _BASEURL ?>contact-us/">Contact</a></li>
								  </ul>
								</div><!--/.nav-collapse -->
							  </div>
							</div> 
						<?php
					}
				
					if (isset($_SESSION['err_message'])) {
						echo '<div class="message_text err_message">' . $_SESSION['err_message'] . '</div>';
						unset($_SESSION['err_message']);
					}
					if (isset($_SESSION['suc_message'])) {
						echo '<div class="message_text suc_message">' . $_SESSION['suc_message'] . '</div>';
						unset($_SESSION['suc_message']);
					}
				?>
				
				<div class="body ">
