<meta charset="UTF-8"/>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title><?php echo $this->getPageTitle(); ?></title>
<meta name="keywords" content="<?php echo $this->getPageMetaKeywords(); ?>">
<meta name="description" content="<?php echo $this->getPageMetadescription(); ?>">
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<script type="text/javascript">var _BASEURL = "<?php echo _BASEURL ?>" </script>
<?php echo $this->renderCss(); ?>
<?php echo $this->renderJs(); ?>
