<?php
$users_list = $this->model->getCollection('users',
                                          array('id', 'name', 'username', 'email', 'user_type', 'is_active', 'last_visit', 'is_root_admin')
);
//debug($users_list);
?>
<div class="container">
    <div class="table mt20">
        <table class="table table-bordered table-striped bs-table">
            <thead class="alert alert-info">
            <tr>
                <th class="tc">Id</th>
                <th class="tc">Name</th>
                <th class="tc">Username</th>
                <th class="tc">Email</th>
                <th class="tc">User type</th>
                <th class="tc">Is active</th>
                <th class="tc">Last visited</th>
                <th class="tc"></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($users_list as $key => $user) { ?>
                <tr>
                    <td class="tc"><?php echo $user['id']; ?></td>
                    <td class="tc"><?php echo $user['name']; ?></td>
                    <td class="tc"><?php echo $user['username']; ?></td>
                    <td class="tc"><?php echo $user['email']; ?></td>
                    <td class="tc"><?php echo $user['user_type']; ?></td>
                    <td class="tc"><?php echo $user['is_active']; ?></td>
                    <td class="tc"><?php echo $user['last_visit']; ?></td>
                    <td class="tc"><?php if ($user['is_root_admin'] != '1') { ?><a
                            href="<?php echo $this->getBaseUrl(); ?>dashboard/edit_users/id/<?php echo $user['id']; ?>">
                                Edit</a><?php } ?></td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>
