<?php
//debug($data);
?>
<body
    style="background:#F6F6F6; font-family:Verdana, Arial, Helvetica, sans-serif; font-size:12px; margin:0; padding:0;">
<div
    style="background:#F6F6F6; font-family:Verdana, Arial, Helvetica, sans-serif; font-size:12px; margin:0; padding:0;">
    <table cellspacing="0" cellpadding="0" border="0" height="100%" width="100%">
        <tr>
            <td align="center" valign="top" style="padding:20px 0 20px 0">
                <!-- [ header starts here] -->
                <table bgcolor="FFFFFF" cellspacing="0" cellpadding="10" border="0" width="650"
                       style="border:1px solid #E0E0E0;">
                    <tr>
                        <td valign="top">
                            <a href="<?php echo _BASEURL; ?>" target="_blank">
                                <img src="<?php echo _BASEURL . 'media/ebdus-logo.png'; ?>"
                                     alt="" style="margin-bottom:10px;"
                                     border="0"/>
                            </a>
                        </td>
                    </tr>
                    <!-- [ middle starts here] -->
                    <tr>
                        <td valign="top">
                            <h1 style="font-size:22px; font-weight:normal; line-height:22px; margin:0 0 11px 0;">
                                Dear Admin,</h1>

                            <p style="font-size:12px; line-height:16px; margin:0 0 16px 0;">
                                We have Received a New Message from<br>
                                <a href="<?php echo _BASEURL; ?>"><?php echo _BASEURL; ?>contact-us</a>
                            </p>

                            <p>Details as Follows:</p>
                        </td>
                    </tr>
                    <tr>
                        <td style="border:1px solid #E0E0E0; font-size:12px; line-height:16px; margin:0; padding:13px 18px; background:#f9f9f9; height: auto;">
                            <table border="1" cellspacing="0" cellpadding="10" width="650"
                                   style="border:1px solid #E0E0E0; font-size: 12px;">
                                <tr>
                                    <td colspan="2" align="center"><b>Message Information</b></td>
                                </tr>
                                <tr>
                                    <td style="width: 95px;"><strong>First Name</strong>:</td>
                                    <td><?php echo $data['firstname']; ?></td>
                                </tr>
                                <tr>
                                    <td><strong>Last Name</strong>:</td>
                                    <td><?php echo $data['lastname']; ?></td>
                                </tr>
                                <tr>
                                    <td><strong>Email</strong>:</td>
                                    <td><?php echo $data['email']; ?></td>
                                </tr>
                                <tr>
                                    <td><strong>Phone</strong>:</td>
                                    <td><?php echo $data['phone']; ?></td>
                                </tr>
                                <tr>
                                    <td><strong>Message</strong>:</td>
                                    <td><?php echo $data['message']; ?></td>
                                </tr>
                                <tr>
                                    <td><strong>Email</strong>:</td>
                                    <td><a href="<?php echo $data['website']; ?>"><?php echo $data['website']; ?></a>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td valign="top">
                            <p style="font-size:12px; line-height:16px; margin:0;"></p>
                        </td>
                    </tr>
                    <tr>
                        <td bgcolor="#EAEAEA" align="center" style="background:#EAEAEA; text-align:center;">
                            <p style="font-size:12px; margin:0;"><strong>Thank you</strong></p>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>
</body>