<?php
$task_detail = $params['task_detail'];
$user_details = $params['user_detail'];
$task_id = $params['task_id'];
?>
<body
    style="background:#F6F6F6; font-family:Verdana, Arial, Helvetica, sans-serif; font-size:12px; margin:0; padding:0;">
<div
    style="background:#F6F6F6; font-family:Verdana, Arial, Helvetica, sans-serif; font-size:12px; margin:0; padding:0;">
    <table cellspacing="0" cellpadding="0" border="0" height="100%" width="100%">
        <tr>
            <td align="center" valign="top" style="padding:20px 0 20px 0">
                <!-- [ header starts here] -->
                <table bgcolor="FFFFFF" cellspacing="0" cellpadding="10" border="0" width="650"
                       style="border:1px solid #E0E0E0;">
                    <tr>
                        <td valign="top">
                            <a href="<?php echo _BASEURL; ?>" target="_blank">
                                <img src="<?php echo _BASEURL . 'media/ebdus-logo.png'; ?>"
                                     alt="<?php echo $user_details['title']; ?>" style="margin-bottom:10px;"
                                     border="0"/>
                            </a>
                        </td>
                    </tr>
                    <!-- [ middle starts here] -->
                    <tr>
                        <td valign="top">
                            <h1 style="font-size:22px; font-weight:normal; line-height:22px; margin:0 0 11px 0;">
                                Dear <?php echo $user_details['emp_name']; ?>,</h1>

                            <p style="font-size:12px; line-height:16px; margin:0 0 16px 0;">You have been created a new
                                task. Please find below the task details.</p>
                        </td>
                    </tr>
                    <tr>
                        <td style="border:1px solid #E0E0E0; font-size:12px; line-height:16px; margin:0; padding:13px 18px; background:#f9f9f9; height: auto;">
                            <table border="1" cellspacing="0" cellpadding="10" width="650"
                                   style="border:1px solid #E0E0E0;">
                                <tr>
                                    <td colspan="2" align="center"><b>Task Information</b></td>
                                </tr>
                                <tr>
                                    <td><strong>Task Name</strong>:</td>
                                    <td><?php echo $task_detail['tsk_name']; ?></td>
                                </tr>
                                <tr>
                                    <td><strong>Task Description</strong>:</td>
                                    <td> <?php echo $task_detail['tsk_desc']; ?></td>
                                </tr>
                                <tr>
                                    <td><strong>Module Name</strong>:</td>
                                    <td><?php echo $task_detail['mod_name']; ?></td>
                                </tr>
                                <tr>
                                    <td><strong>Task URL</strong>:</td>
                                    <td>
                                        <a href="<?php echo _BASEURL . 'projects/tasksdetail/id/' . $task_id; ?>"><?php echo $task_detail['tsk_name']; ?></a>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td valign="top">
                            <p style="font-size:12px; line-height:16px; margin:0;"></p>
                        </td>
                    </tr>
                    <tr>
                        <td bgcolor="#EAEAEA" align="center" style="background:#EAEAEA; text-align:center;">
                            <center><p style="font-size:12px; margin:0;">Thank you again,
                                    <strong><?php echo $user_details['title']; ?></strong></p></center>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>
</body>