<div class="page_width">
	<div class="login fl cb">
		
		<div class='login_box fl cb form-signin'>
			<p class="signin">EMS - Please Sign In</p> 
			<form id="login_form" class="" action="<?php echo _BASEURL ?>users/login/" method="post" enctype="multipart/form-data">
				<div class="input-group">
					<span class="input-group-addon  input_img_icon"><i class="icon-envelope"></i></span>
					<input type="email" class="form-control" required="" placeholder="Email Address" name="email" />
				</div>
				<br>
				<div class="input-group">
					<span class="input-group-addon  input_img_icon"><i class="icon-lock"></i></span>
					<input type="password" class="form-control" required="" placeholder="Password" name="password" />
				</div>
				<p class="pull-right"><a data-toggle="modal" href="#resetPassword">Reset Password</a></p>
				<button type="input" name="submit" value="signIn" class="login_btn btn btn-info btn-icon"><i class="icon-signin"></i> Please Sign In</button>
			</form>
		</div>
		
		<div class="modal fade" id="resetPassword" tabindex="-1" role="dialog" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i></button>
						<h4 class="modal-title">Reset Password</h4>
					</div>
					<form id="frgtpswd_form" action="" method="post">
						<div class="modal-body">
							<div class="form-group">
								<label for="theEmail">Email Address</label>
								<input type="email" class="form-control" required="" name="email" id="theEmail" value="">
								<span class="help-block">The email address associated with your account.</span>
							</div>
						</div>
						<div class="modal-footer">
							<button type="input" name="submit" value="resetPass" class="btn btn-success btn-icon"><i class="icon-unlock"></i> Reset Password</button>
							<button type="button" class="fpswd_btn btn btn-default btn-icon" data-dismiss="modal"><i class="icon-remove-sign"></i> Cancel</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
