<div class="container">
    <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
		<div class="panel panel-info" >
			<div class="panel-heading">
				<div class="panel-title">Enter Your Email Id..!</div>			
			</div>
			<div style="padding-top:30px" class="panel-body" >
				<form id="loginform" class="form-horizontal" action="<?php echo $this->getBaseUrl(); ?>users/forget_password" method="POST" role="form">
					<div style="margin-bottom: 25px" class="input-group">
						<span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
						<input id="login-username" type="text" class="form-control" name="email" value="" placeholder="email">                                        
					</div>				
					<div style="margin-top:10px" class="form-group">
						<!-- Button -->
						<div class="col-sm-12 controls">
						  <button id="btn-login" type="submit" class="btn btn-success">Submit</button>
						</div>
					</div>
				</form>     
			</div>                     
		</div>  
	</div>
</div>