<?php 
	$current_user = $this->getData('current_user');
	// debug($current_user);
?>
<div class="container">
	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >
			<div class="panel panel-info">
				<div class="panel-heading">
				  <h3 class="panel-title"><?php echo $current_user['name']; ?></h3>
				</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-md-3 col-lg-3 " align="center">
							<img alt="User Pic" src="<?php echo $this->getBaseUrl(); ?>media/empty-avatar-male.png" class="img-circle">
						</div>					
						<div class=" col-md-9 col-lg-9 "> 
						  <table class="table table-user-information">
							<tbody>
							  <tr>
								<td>Username:</td>
								<td><?php echo $current_user['username']; ?></td>
							  </tr>
							  <tr>
								<td>Email:</td>
								<td><?php echo $current_user['email']; ?></td>
							  </tr>
							  <tr>
								<td>Gender:</td>
								<td><?php echo $current_user['gender']; ?></td>
							  </tr>
							  <tr>
								<td>Address:</td>
								<td><?php echo $current_user['address']; ?></td>
							  </tr>
							  <tr>
								<td>Contact:</td>
								<td><?php echo $current_user['contact_no']; ?></td>
							  </tr>
							  <tr>
								<td>Date of Birth:</td>
								<td><?php echo $current_user['dob']; ?></td>
							  </tr>
							  <tr>
								<td>Last Login:</td>
								<td><?php echo $current_user['last_visit']; ?></td>
							  </tr>
							</tbody>
						  </table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
