<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body class="<?php echo $this->getBodyClass(); ?>">
<div class="wrapper">
    <?php echo $this->getChildHtml('notices') ?>
    <div class="page">
        <?php echo $this->getChildHtml('header') ?>
        <div class="main-container col2-left-layout">
            <div class="main">

                <div class="sidebar left">
                    <?php echo $this->getChildHtml('left') ?>
                </div>
                <div class="col-main">
                    <?php echo $this->getChildHtml('content') ?>
                </div>
            </div>
        </div>
        <?php echo $this->getChildHtml('footer') ?>
    </div>
</div>
</body>
</html>