<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title><?php echo $this->getPageTitle(); ?></title>
</head>
<body class="<?php echo $this->getBodyClass(); ?>">
<div class="wrapper">
    <div class="page">
        Installer has to be added. Now manually load the db from  <?php echo 'app/code/sql/db-install.sql'; ?> into your
        mysql and update local.xml please
    </div>
</div>
</body>
</html>