<?php 
	 if (Template::$headerFile != '' && file_exists($headerFileName = Template::$templatePath.'global/'.Template::$headerFile.".phtml")){
		include_once($headerFileName);
	 }
?>	 
<div class="body layout_<?php echo Template::$layout; ?>">
	<div class="content">
		<div class="main">
		<?php 	 
			 // include_once(Template::$templatePath."global/messages.phtml");
			 if (Template::$contentFile != '' && file_exists($contentFileName = self::$templatePath.$module."/".self::$contentFile.".phtml")){
				include_once($contentFileName);
			 }
			 else{
				include_once(self::$templatePath.$module."/global/error_404.phtml");
			 }
		?>
		</div>	
	</div>		
</div>
<?php 	 
	 if (Template::$footerFile != '' && file_exists($footerFileName = Template::$templatePath.'global/'.Template::$footerFile.".phtml")){
		include_once($footerFileName);
	 }
?>
