<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body class="<?php echo $this->getBodyClass(); ?>">
<div class="wrapper">
    <div class="page">
        <div class="main-container col1-layout">
            <div class="main">
                <div class="col-main">
                    <?php echo $this->getChildHtml("global_messages") ?>
                    <?php echo $this->getChildHtml("content") ?>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>