<div class="container">
    <h1>Create New Page</h1>

    <div class="fr" style="margin-top: -30px;">
        <a href="<?php echo $this->getBaseUrl(); ?>cms/index" ><i class="glyphicon glyphicon-chevron-left"></i> Back to Pages List</a>
    </div>

    <hr>
    <div class="row">
        <!-- edit form column -->
        <div class="col-md-9 personal-info">
            <h3>Page Info</h3>
            <form class="form-horizontal" role="form" action="<?php echo $this->getBaseUrl(); ?>cms/createpage" method="POST">
                <div class="form-group">
                    <label class="col-lg-3 control-label">Title:</label>
                    <div class="col-lg-8">
                        <input value="" name="page_id" type="hidden">
                        <input class="form-control" value="" name="title" type="text" required>
                    </div>
                </div>
                <div class="form-group">
                    <label for="root_template" class="col-md-3 control-label">Root Template:</label>
                    <div class="col-md-8">
                        <select class="form-control" name="root_template" required>
                            <?php $templates = Utils::rootTemplates();
                            foreach($templates as $key=>$template){ ?>
                                <option value="<?php echo $key; ?>" ><?php echo $template; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">META Keywords:</label>
                    <div class="col-lg-8">
                        <textarea class="form-control" value="" name="meta_keywords" type="text"></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">META Description:</label>
                    <div class="col-lg-8">
                        <textarea class="form-control" value="" name="meta_description" type="text" ></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">Identifier:</label>
                    <div class="col-lg-8">
                        <input class="form-control" value="" name="identifier" type="text" required>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">Content Heading:</label>
                    <div class="col-lg-8">
                        <input class="form-control" value="" name="content_heading" type="text">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">Content:</label>
                    <div class="col-lg-8">
                        <textarea class="form-control" rows="10" value="" name="content" type="text"></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label for="is_active" class="col-md-3 control-label">Is Active:</label>
                    <div class="col-md-8">
                        <select class="form-control" name="is_active" required>
                            <?php $yes_nos = Utils::yesNoOptions();
                            foreach($yes_nos as $key=>$yes_no){ ?>
                                <option value="<?php echo $key; ?>" ><?php echo $yes_no; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label"></label>
                    <div class="col-md-8">
                        <input class="btn btn-primary" value="Save Changes" type="submit">
                        <span></span>
                        <input class="btn btn-default" value="Cancel" type="reset">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<hr>