<?php
$all_cms_pages = $this->getData('all_cms_pages');
//debug($all_cms_pages);
?>
<div class="container">
    <div class="fr mt30 mb10">
        <a href="<?php echo $this->getBaseUrl(); ?>cms/createpage" class="btn btn-success"><i
                class="glyphicon glyphicon-plus"></i> Create New Page</a>
    </div>
    <div class="table mt20 fl">
        <table class="table table-bordered table-striped bs-table">
            <thead class="alert alert-info">
            <tr>
                <th class="tc">ID</th>
                <th class="tc">Title</th>
                <th class="tc">Template</th>
                <th class="tc">Url</th>
                <th class="tc">Is Active</th>
                <th class="tc">Last Updated</th>
                <th class="tc"></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($all_cms_pages as $key => $cms_page) { ?>
                <tr>
                    <td class="tc"><?php echo $cms_page['page_id']; ?></td>
                    <td class="tc"><?php echo $cms_page['title']; ?></td>
                    <td class="tc"><?php echo $cms_page['root_template']; ?></td>
                    <td class="tc"><?php echo $cms_page['identifier']; ?></td>
                    <td class="tc"><?php echo $cms_page['is_active']; ?></td>
                    <td class="tc"><?php echo $cms_page['update_time']; ?></td>
                    <td class="tc"><a href="<?php echo $this->getBaseUrl(
                        ); ?>cms/editpage/id/<?php echo $cms_page['page_id']; ?>">Edit</a></td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>
