<?php
// d($params);
// d($module);
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title><?php echo $app->getPageTitle(); ?></title>
    <meta name="keywords" content="<?php echo $app->getPageMetaKeywords(); ?>">
    <meta name="description" content="<?php echo $app->getPageMetadescription(); ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <script type="text/javascript">var _BASEURL = "<?php echo _BASEURL ?>" </script>
    <?php echo $app->renderCss(); ?>
    <?php echo $app->renderJs(); ?>
</head>

<body class="<?php echo $app->getBodyClass(); ?>">

<div class="wrapper">
    <div class="page">
        <div role="navigation" class="header navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <a href="<?php echo $app->getBaseUrl(); ?>" class="navbar-brand"><?php echo $app->getSiteTitle(
                        ); ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $app->getBaseUrl(); ?>">Admin Home</a></li>
                    </ul>
                </div>
            </div>
        </div>
				
