<?php

//Template level Model access
// $usersList = $this->model->getUsers();
// debug($usersList);

// Sample controller level Function call
// $usersList = $this->_sampleControllerFunction();

// Sample Block level Function call
//$usersList = $this->getDataFromBlock();
//debug($usersList);
$adminUser = $this->model->isAdminLoggedIn();
?>
<?php if ($adminUser) { ?>
    <div role="navigation" class="header navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a href="<?php echo $this->getBaseUrl(); ?>" class="navbar-brand"><?php echo $this->getSiteTitle(); ?></a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="<?php echo $this->getBaseUrl(); ?>">Home</a></li>
                    <li><a href="<?php echo $this->getBaseUrl(); ?>cms/index/">CMS</a></li>
                    <li><a href="<?php echo $this->getBaseUrl(); ?>dashboard/account/">My Account</a></li>
                    <li><a href="<?php echo $this->getBaseUrl(); ?>dashboard/users/">Users</a></li>
                    <li><a href="<?php echo $this->getBaseUrl(); ?>dashboard/system/">System</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="<?php echo $this->getBaseUrl(); ?>dashboard/logout">Logout</a></li>
                </ul>
            </div>
        </div>
    </div>
<?php
} else {
    ?>
    <div role="navigation" class="header navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a href="<?php echo $this->getBaseUrl(); ?>" class="navbar-brand"><?php echo $this->getSiteTitle(); ?></a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="<?php echo _BASEURL; ?>">Home</a></li>
                    <li><a href="<?php echo $this->getBaseUrl(); ?>dashboard/login/">Admin Login</a></li>
                </ul>
            </div>
        </div>
    </div>
<?php
}
?>
<?php echo $this->getChildHtml('messages') ?>
