<?php
//Template level Model access
// $usersList = $this->model->getUsers();
// debug($usersList);
// Sample controller level Function call
// $usersList = $this->_sampleControllerFunction();
?>
<?php if ($this->model && $this->model->isUserLoggedIn()) { ?>
    <div role="navigation" class="header navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a href="<?php echo $this->getBaseUrl(); ?>" class="navbar-brand"><?php echo $this->siteTitle; ?></a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="<?php echo $this->getBaseUrl(); ?>">Home</a></li>
                    <li><a href="<?php echo $this->getBaseUrl(); ?>cms/index/">CMS</a></li>
                    <li><a href="<?php echo $this->getBaseUrl(); ?>admin/profile/">My Account</a></li>
                    <li><a href="<?php echo $this->getBaseUrl(); ?>admin/system/">System</a></li>
                </ul>
            </div>
        </div>
    </div>
<?php
} else {
    ?>
    <div role="navigation" class="header navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a href="<?php echo $this->getBaseUrl(); ?>" class="navbar-brand"><?php echo $this->siteTitle; ?></a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="<?php echo $this->getBaseUrl(); ?>">Home</a></li>
                    <li><a href="<?php echo $this->getBaseUrl(); ?>users/login/">Login</a></li>
                </ul>
            </div>
        </div>
    </div>
<?php
}
?>

<?php echo $this->getChildHtml('messages') ?>
