<?php
if ($errorMessages = parent::getSession('err_message')) {
    echo '<div class="container alert alert-danger " role="alert">
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>' . $errorMessages . '</div>';
    parent::setSession('err_message');
}
if ($successMessages = parent::getSession('suc_message')) {
    echo '<div class="container alert alert-success " role="alert">
        <span class="glyphicon glyphicon-bell" aria-hidden="true"></span>' . $successMessages . '</div>';
    parent::setSession('suc_message');
}
?>
