<div class="page_width">
    <div class="login fl cb">
        <div class='login_box fl cb form-signin'>
            <p class="signin">Please Sign In</p>

            <form id="login_form" class="" action="<?php echo _BASEURL ?>users/login/" method="post"
                  enctype="multipart/form-data">
                <div class="input-group">
                    <span class="input-group-addon  input_img_icon"><i class="icon-envelope"></i></span>
                    <input type="email" class="form-control" required="" placeholder="Email Address" name="email"/>
                </div>
                <br>

                <div class="input-group">
                    <span class="input-group-addon  input_img_icon"><i class="icon-lock"></i></span>
                    <input type="password" class="form-control" required="" placeholder="Password" name="password"/>
                </div>
                <button type="input" name="submit" value="signIn" class="login_btn btn btn-info btn-icon"><i
                        class="icon-signin"></i> Please Sign In
                </button>
            </form>
        </div>
    </div>
</div>
