<?php
$user_config = $this->model->getConfigData();
//debug($user_config);
?>
<div class="container">
    <h1>Config Settings</h1>
    <div class="fr" style="margin-top: -30px;">
        <a href="<?php echo $this->getBaseUrl(); ?>admin/clearcache/option/adminhtml" class="btn btn-info" >Clear Admin Cache</a>
        <a href="<?php echo $this->getBaseUrl(); ?>admin/clearcache/option/frontend" class="btn btn-warning" >Clear Frontend Cache</a>
    </div>
    <hr>
    <div class="row">
        <!-- edit form column -->
        <div class="col-md-9 personal-info">
            <div class="alert alert-info alert-dismissable dn">
                <a class="panel-close close" data-dismiss="alert">×</a>
                <i class="fa fa-coffee"></i>
                This is an <strong>.alert</strong>. Use this to show important messages to the user.
            </div>
            <h3>System Configuration</h3>

            <form class="form-horizontal" role="form" action="<?php echo $this->getBaseUrl(); ?>admin/system" method="POST">
                <div class="form-group">
                    <label for="enable_email" class="col-md-3 control-label">Enable EMAIL:</label>
                    <div class="col-md-8">
                        <select class="form-control" name="enable_email">
                            <?php $yes_nos = Utils::yesNoOptions();
                            foreach($yes_nos as $key=>$yes_no){ ?>
                                <option value="<?php echo $key; ?>" <?php if(isset($user_config['enable_email']) && $user_config['enable_email'] == $key){echo 'selected';}?> ><?php echo $yes_no; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">Contact EMAIL:</label>
                    <div class="col-lg-8">
                        <input class="form-control" value="<?php if(isset($user_config['contact_email'])){echo $user_config['contact_email'];} ?>" name="contact_email" type="text">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">Contact Person NAME:</label>
                    <div class="col-lg-8">
                        <input class="form-control" value="<?php if(isset($user_config['contact_name'])){echo $user_config['contact_name'];} ?>" name="contact_name" type="text">
                    </div>
                </div>
                <div class="form-group">
                    <label for="print_execution_order" class="col-md-3 control-label">Enable PROFILER:</label>
                    <div class="col-md-8">
                        <select class="form-control" name="print_execution_order">
                            <?php $yes_nos = Utils::yesNoOptions();
                            foreach($yes_nos as $key=>$yes_no){ ?>
                                <option value="<?php echo $key; ?>" <?php if(isset($user_config['print_execution_order']) && $user_config['print_execution_order'] == $key){echo 'selected';}?> ><?php echo $yes_no; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">Site TITLE:</label>
                    <div class="col-lg-8">
                        <input class="form-control" value="<?php if(isset($user_config['site_title'])){echo $user_config['site_title'];} ?>" name="site_title" type="text">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">Site META Description:</label>
                    <div class="col-lg-8">
                        <textarea class="form-control" value="<?php if(isset($user_config['site_meta_description'])){echo $user_config['site_meta_description'];} ?>" name="site_meta_description" type="text"><?php echo $user_config['site_meta_description']; ?></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">Site META Keywords:</label>
                    <div class="col-lg-8">
                        <textarea class="form-control" value="<?php if(isset($user_config['site_meta_keywords'])){echo $user_config['site_meta_keywords'];} ?>" name="site_meta_keywords" type="text"><?php echo $user_config['site_meta_keywords']; ?></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label for="js_compress" class="col-md-3 control-label">Enable JS Compression:</label>
                    <div class="col-md-8">
                        <select class="form-control" name="js_compress">
                            <?php $yes_nos = Utils::yesNoOptions();
                            foreach($yes_nos as $key=>$yes_no){ ?>
                                <option value="<?php echo $key; ?>" <?php if(isset($user_config['js_compress']) && $user_config['js_compress'] == $key){echo 'selected';}?> ><?php echo $yes_no; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="css_compress" class="col-md-3 control-label">Enable CSS Compression:</label>
                    <div class="col-md-8">
                        <select class="form-control" name="css_compress">
                            <?php $yes_nos = Utils::yesNoOptions();
                            foreach($yes_nos as $key=>$yes_no){ ?>
                                <option value="<?php echo $key; ?>" <?php if(isset($user_config['css_compress']) && $user_config['css_compress'] == $key){echo 'selected';}?> ><?php echo $yes_no; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="html_compress" class="col-md-3 control-label">Enable HTML Compression:</label>
                    <div class="col-md-8">
                        <select class="form-control" name="html_compress">
                            <?php $yes_nos = Utils::yesNoOptions();
                            foreach($yes_nos as $key=>$yes_no){ ?>
                                <option value="<?php echo $key; ?>" <?php if(isset($user_config['html_compress']) && $user_config['html_compress'] == $key){echo 'selected';}?> ><?php echo $yes_no; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label"></label>
                    <div class="col-md-8">
                        <input class="btn btn-primary" value="Save Changes" type="submit">
                        <span></span>
                        <input class="btn btn-default" value="Cancel" type="reset">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<hr>