<?php

?>
						<div class="page_width">
							<div class="footer fl cb">
								<div class="footer_container fl cb">
									<div class="fl cb">
										<div class="footer_links fl cb ">
												<p>&copy; 2014 Ebdus Employee Management System</p>
										</div>
									</div>
								</div>
							</div>
						</div>
                    </div>
				</div>
			</div>
		</div>
	</body>
</html>