<?php
// d($params);
// d($module);
?>
<!DOCTYPE html>
<html>

    <head>
        <meta charset="UTF-8"/>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?php echo $_SESSION['title'] ?></title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		
		<link type="text/css" rel="stylesheet" href="<?php echo _BASEURL ?>skin/frontend/css/dropzone.css" />
		<link type="text/css" rel="stylesheet" href="<?php echo _BASEURL ?>skin/frontend/css/jquery-te-1.4.0.css"/>
		<link rel="stylesheet" type="text/css" href="<?php echo _BASEURL ?>skin/frontend/css/bootstrap.css"/>
		<link rel="stylesheet" type="text/css" href="<?php echo _BASEURL ?>skin/frontend/css/custom.css"/>
		
		
		<script type="text/javascript">
			var  _BASEURL ="<?php echo _BASEURL ?>"
		</script>
		
        <script type="text/javascript" src="<?php echo _BASEURL ?>skin/frontend/js/jquery-1.9.1.min.js"></script>
		<script type="text/javascript" src="<?php echo _BASEURL ?>skin/frontend/js/bootstrap.js"></script>
		<script type="text/javascript" src="<?php echo _BASEURL ?>skin/frontend/js/dropzone.js"></script>
		<script type="text/javascript" src="<?php echo _BASEURL ?>skin/frontend/js/jquery-te-1.4.0.min.js"></script>
        <script type="text/javascript" src="<?php echo _BASEURL ?>skin/frontend/js/scripts.js"></script>
		
    </head>  


    <body class="<?php echo $_SESSION['body_class']; ?>">

        <div id="wrapper">
            <div id="container">
                <div id="page">
					<?php if(isset($_SESSION['emp_name'])) { ?>
						
						<div role="navigation" class="navbar navbar-inverse navbar-fixed-top">
						  <div class="container">
							<div class="navbar-header">
							  <a href="#" class="navbar-brand">EMS</a>
							</div>
							<div class="collapse navbar-collapse">
							  <ul class="nav navbar-nav">
								<li class="active"><a href="#">Home</a></li>
								<li><a href="<?php echo _BASEURL ?>projects/list">Projects</a></li>
								<li><a href="<?php echo _BASEURL ?>reports/status_report/">Status Report</a></li>												
								<li><a href="<?php echo _BASEURL ?>attendance/leave/">Leave Form</a></li>
								<li><a href="#contact">Contact</a></li>
							  </ul>
							</div><!--/.nav-collapse -->
						  </div>
						</div> 
					<?php
					}
					else{
						?>
							<div role="navigation" class="navbar navbar-inverse navbar-fixed-top">
							  <div class="container">
								<div class="navbar-header">
								  <a href="#" class="navbar-brand">EMS</a>
								</div>
								<div class="collapse navbar-collapse">
								  <ul class="nav navbar-nav">
									<li><a href="<?php echo _BASEURL ?>">Home</a></li>
									<li><a href="<?php echo _BASEURL ?>users/login">Login</a></li>
									<li><a href="#contact">Contact</a></li>
								  </ul>
								</div><!--/.nav-collapse -->
							  </div>
							</div> 
						<?php
					}
				
					if (isset($_SESSION['err_message'])) {
						echo '<div class="message_text err_message">' . $_SESSION['err_message'] . '</div>';
						unset($_SESSION['err_message']);
					}
					if (isset($_SESSION['suc_message'])) {
						echo '<div class="message_text suc_message">' . $_SESSION['suc_message'] . '</div>';
						unset($_SESSION['suc_message']);
					}
				?>
				
				<div class="body container">
